import type { ProduceEventHandler } from '@application/commands/produce-event-handler.js';
import type { CreateTopicHandler } from '@application/commands/create-topic-handler.js';
import type { GetTopicHandler } from '@application/handlers/get-topic-handler.js';
import type { UpdateTopicHandler } from '@application/handlers/update-topic-handler.js';
import type { DeleteTopicHandler } from '@application/handlers/delete-topic-handler.js';
import type { CreatePushConsumerHandler } from '@application/commands/create-push-consumer-handler.js';
import type { CreatePullConsumerHandler } from '@application/commands/create-pull-consumer-handler.js';
import type { CreateScheduleHandler } from '@application/commands/create-schedule-handler.js';
import type { CreateApiKeyHandler } from '@application/commands/create-api-key-handler.js';
import type { ListApiKeysHandler } from '@application/queries/list-api-keys-handler.js';
import type { GetApiKeyHandler } from '@application/queries/get-api-key-handler.js';
import type { DeleteApiKeyHandler } from '@application/handlers/delete-api-key-handler.js';
import type { RegisterTenantHandler } from '@application/commands/register-tenant-handler.js';
import type { ListEventsHandler } from '@application/queries/list-events-handler.js';
import type { GetEventDetailHandler } from '@application/queries/get-event-detail-handler.js';
import type { ListTopicsHandler } from '@application/queries/list-topics-handler.js';
import type { ListConsumersHandler } from '@application/queries/list-consumers-handler.js';
import type { ListSchedulesHandler } from '@application/queries/list-schedules-handler.js';
import type { GetDashboardMetricsHandler } from '@application/queries/get-dashboard-metrics-handler.js';
import type { LoginHandler } from '@application/handlers/login-handler.js';
import type { RefreshTokenHandler } from '@application/handlers/refresh-token-handler.js';
import type { LogoutHandler } from '@application/handlers/logout-handler.js';
import type { CreateUserHandler } from '@application/handlers/create-user-handler.js';
import type { GetCurrentUserHandler } from '@application/handlers/get-current-user-handler.js';
import type { UpdateUserHandler } from '@application/handlers/update-user-handler.js';
import type { ChangePasswordHandler } from '@application/handlers/change-password-handler.js';
import type { ConsumeEventsHandler } from '@application/handlers/consume-events-handler.js';
import type { GetTenantHandler } from '@application/handlers/get-tenant-handler.js';
import type { UpdateTenantHandler } from '@application/handlers/update-tenant-handler.js';
import type { GetUsageHandler } from '@application/handlers/get-usage-handler.js';
import type { ListDeadLetterEventsHandler } from '@application/handlers/list-dead-letter-events-handler.js';
import type { ReplayDeadLetterEventHandler } from '@application/handlers/replay-dead-letter-event-handler.js';
import type { GetConsumerHealthHandler } from '@application/handlers/get-consumer-health-handler.js';
import type { GetConsumerHandler } from '@application/handlers/get-consumer-handler.js';
import type { UpdateConsumerHandler } from '@application/handlers/update-consumer-handler.js';
import type { DeleteConsumerHandler } from '@application/handlers/delete-consumer-handler.js';
import type { PauseConsumerHandler } from '@application/handlers/pause-consumer-handler.js';
import type { ResumeConsumerHandler } from '@application/handlers/resume-consumer-handler.js';
import type { AcknowledgeEventHandler } from '@application/handlers/acknowledge-event-handler.js';

export interface ApplicationHandlers {
  produceEvent:            ProduceEventHandler;
  createTopic:             CreateTopicHandler;
  getTopic:                GetTopicHandler;
  updateTopic:             UpdateTopicHandler;
  deleteTopic:             DeleteTopicHandler;
  createPushConsumer:      CreatePushConsumerHandler;
  createPullConsumer:      CreatePullConsumerHandler;
  createSchedule:          CreateScheduleHandler;
  createApiKey:            CreateApiKeyHandler;
  listApiKeys:             ListApiKeysHandler;
  getApiKey:               GetApiKeyHandler;
  deleteApiKey:            DeleteApiKeyHandler;
  registerTenant:          RegisterTenantHandler;
  listEvents:              ListEventsHandler;
  getEventDetail:          GetEventDetailHandler;
  listTopics:              ListTopicsHandler;
  listConsumers:           ListConsumersHandler;
  listSchedules:           ListSchedulesHandler;
  getDashboardMetrics:     GetDashboardMetricsHandler;
  login:                   LoginHandler;
  refresh:                 RefreshTokenHandler;
  logout:                  LogoutHandler;
  createUser:              CreateUserHandler;
  getCurrentUser:          GetCurrentUserHandler;
  updateUser:              UpdateUserHandler;
  changePassword:          ChangePasswordHandler;
  consumeEvents:           ConsumeEventsHandler;
  getTenant:               GetTenantHandler;
  updateTenant:            UpdateTenantHandler;
  getUsage:                GetUsageHandler;
  listDeadLetterEvents:    ListDeadLetterEventsHandler;
  replayDeadLetterEvent:   ReplayDeadLetterEventHandler;
  getConsumerHealth:       GetConsumerHealthHandler;
  getConsumer:             GetConsumerHandler;
  updateConsumer:          UpdateConsumerHandler;
  deleteConsumer:          DeleteConsumerHandler;
  pauseConsumer:           PauseConsumerHandler;
  resumeConsumer:          ResumeConsumerHandler;
  acknowledgeEvent:        AcknowledgeEventHandler;
}
